base_model: Salesforce/codet5-base
# base_model: Salesforce/codet5p-220m
debug_mode: False
#
generation:
  max_new_tokens: 512
  do_sample: True
  temperature: 2.0
  num_beams: 1
  tokenizer: roberta # or auto
#
fine_tuning:
  output_dir: models
  learning_rate: 1e-5
  num_train_epochs: 100
  weight_decay: 0.01
  logging_steps: 100
  max_steps: 100
#
preprocess:
  db_file: data/FixMe-v1.db
  max_hunks_per_url: 2
  # CodeT5 supported: Python, Java, JavaScript, PHP, Ruby, Go, C, and C#
  prog_lang: # list of programming languages
    - C
    - C++
    # - Python
    # - Java
    # - JavaScript
    # - PHP
    # - Ruby
    # - Go
    # - C#
