# base_model: Salesforce/codet5-base
# base_model: codellama/CodeLlama-7b-Instruct-hf
base_model: models/CodeLLama-7b-quantized-4bit
# most lightweight model of CodeLlama for instruction prompt
debug_mode: True
use_4bit_quantization: True
#
generation:
  max_new_tokens: 512
  do_sample: True
  temperature: 2.0
  num_beams: 1
  tokenizer: roberta # or auto
#
fine_tuning:
  output_dir: models
  learning_rate: 1e-3
  num_train_epochs: 10
  batch_size: 8
  per_device_train_bsize: 4
  weight_decay: 0.01
  logging_steps: 100
  max_steps: 10
#
preprocess:
  db_file: data/FixMe-v1.db
  max_hunks_per_url: 1
  # CodeT5 supported: Python, Java, JavaScript, PHP, Ruby, Go, C, and C#
  prog_lang: # list of programming languages
    - C
    - C++
    # - Python
    # - Java
    # - JavaScript
    # - PHP
    # - Ruby
    # - Go
    # - C#
